---
name: CI for pull requests

"on":
  pull_request:

jobs:
  judge-exec:
    outputs:
      needs-test-go: ${{ steps.judge-needs-test-go.outputs.any_changed }}
      needs-lint-markdown: ${{ steps.judge-needs-lint-markdown.outputs.any_changed }}
      needs-lint-github-actions: ${{ steps.judge-needs-lint-github-actions.outputs.any_changed }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - id: judge-needs-test-go
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: |
            **/*.go
            go.mod
            go.sum
            .github/workflows/task-test-go.yml
      - id: judge-needs-lint-markdown
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: |
            **/*.md
      - id: judge-needs-lint-github-actions
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: |
            .github/actions/**
            .github/workflows/**

  test-go:
    needs: judge-exec
    if: needs.judge-exec.outputs.needs-test-go == 'true'
    permissions:
      contents: read
    uses: ./.github/workflows/task-test-go.yml

  lint-markdown:
    needs: judge-exec
    if: needs.judge-exec.outputs.needs-lint-markdown == 'true'
    permissions:
      contents: read
    uses: ./.github/workflows/task-lint-markdown.yml

  lint-github-actions:
    needs: judge-exec
    if: needs.judge-exec.outputs.needs-lint-github-actions == 'true'
    permissions:
      checks: write
      contents: read
      pull-requests: write
    uses: ./.github/workflows/task-lint-github-actions.yml
