---
name: lint-github-actions

"on":
  workflow_call:

jobs:
  lint:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - uses: reviewdog/action-yamllint@f01d8a48fd8d89f89895499fca2cff09f9e9e8c0 # v1.21.0
        with:
          fail_level: error
          reporter: github-pr-review
      - uses: ne-sachirou/lint-gha-reviewdog@b2173b3f186f624398947e89fe1e6524787983d5 # v0.0.9
        with:
          github_token: ${{ github.token }}
