---
name: lint-yaml

"on":
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: latest
      - name: Lint YAML
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends yamllint
          make lint-yaml
