---
name: test-go

"on":
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
      - uses: golangci/golangci-lint-action@v4
        with:
          skip-pkg-cache: true # https://github.com/golangci/golangci-lint-action/issues/677
          args: --timeout 5m

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: test
        run: make test-go
